package com.blueapps.seshat.svg;

import java.math.BigDecimal;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public final class SVGPathTransformer {

    /**
     * Generated by GitHub Copilot
     */

    private static final Pattern SVG_PATH_TOKEN_PATTERN = Pattern.compile(
            "([A-Za-z])|([-+]?(?:\\d*\\.\\d+|\\d+\\.\\d*|\\d+)(?:[eE][-+]?\\d+)?)"
    );

    private SVGPathTransformer() {
    }

    public static String transformPath(String pathData, double translateX, double translateY,
                                      double scaleX, double scaleY) {
        if (pathData == null || pathData.trim().isEmpty()) {
            return pathData;
        }

        StringBuilder result = new StringBuilder();
        Matcher matcher = SVG_PATH_TOKEN_PATTERN.matcher(pathData);
        char currentCommand = 0;
        int commandIndex = 0;

        while (matcher.find()) {
            String token = matcher.group();

            if (token.length() == 1 && Character.isLetter(token.charAt(0))) {
                if (result.length() > 0 && !Character.isWhitespace(result.charAt(result.length() - 1))) {
                    result.append(' ');
                }
                result.append(token);
                currentCommand = token.charAt(0);
                commandIndex = 0;
                continue;
            }

            if (currentCommand == 0) {
                if (result.length() > 0 && !Character.isWhitespace(result.charAt(result.length() - 1))) {
                    result.append(' ');
                }
                result.append(token);
                continue;
            }

            double value = Double.parseDouble(token);
            int axisIndex = getAxisIndex(currentCommand, commandIndex);

            if (axisIndex == 0) {
                value = value * scaleX + translateX;
            } else if (axisIndex == 1) {
                value = value * scaleY + translateY;
            }

            if (result.length() > 0 && !Character.isWhitespace(result.charAt(result.length() - 1))) {
                result.append(' ');
            }
            result.append(formatNumber(value));
            commandIndex++;
        }

        return result.toString().trim();
    }

    private static int getAxisIndex(char command, int indexInCommand) {
        switch (Character.toLowerCase(command)) {
            case 'm':
            case 'l':
            case 't':
                return indexInCommand % 2 == 0 ? 0 : 1;
            case 'h':
                return 0;
            case 'v':
                return 1;
            case 'c':
                int cubicIndex = indexInCommand % 6;
                if (cubicIndex == 0 || cubicIndex == 2 || cubicIndex == 4) {
                    return 0;
                }
                return 1;
            case 's':
            case 'q':
                int smoothIndex = indexInCommand % 4;
                if (smoothIndex == 0 || smoothIndex == 2) {
                    return 0;
                }
                return 1;
            case 'a':
                int arcIndex = indexInCommand % 7;
                if (arcIndex == 5) {
                    return 0;
                }
                if (arcIndex == 6) {
                    return 1;
                }
                return -1;
            default:
                return -1;
        }
    }

    private static String formatNumber(double value) {
        if (Double.isNaN(value) || Double.isInfinite(value)) {
            return String.valueOf(value);
        }

        if (Math.abs(value) < 1e-12) {
            value = 0d;
        }

        BigDecimal bigDecimal = BigDecimal.valueOf(value).stripTrailingZeros();
        return bigDecimal.toPlainString();
    }
}
